import { manageImages } from './manageImages';

const { src: heroImg } = manageImages.heroImage;
// const images = require("../public/assets/img/hero-img-1.jpg");
// public\assets\img\hero-img-1.jpg

export const styles = {
  app: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    color: '#fff',
    background: '#040b14',
    minHeight: '100vh',
  },
  sidebar: {
    position: 'fixed',
    left: 0,
    top: 0,
    bottom: 0,
    width: '21%',
    display: 'flex',
    flexDirection: 'column',
    background: 'linear-gradient(180deg, rgba(4, 11, 20, 0.95) 0%, rgba(13, 17, 23, 0.92) 100%)',
    backdropFilter: 'blur(12px)',
    borderRight: '1px solid rgba(20, 157, 221, 0.08)',
    overflowY: 'auto',
    zIndex: 1000,
    boxShadow: '0 0 40px rgba(0, 0, 0, 0.4), inset 0 0 80px rgba(20, 157, 221, 0.02)',
  },
  sidebarOpen: {
    transform: 'translateX(0)',
  },
  sidebarContent: {
    padding: '40px 28px',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  profileSection: {
    textAlign: 'center',
    marginBottom: '36px',
    paddingBottom: '28px',
    borderBottom: '1px solid rgba(20, 157, 221, 0.1)',
    position: 'relative',
  },
  profileAccentBar: {
    position: 'absolute',
    bottom: '-1px',
    left: '50%',
    transform: 'translateX(-50%)',
    width: '60px',
    height: '2px',
    background: 'linear-gradient(90deg, transparent, rgb(20, 157, 221), transparent)',
    borderRadius: '2px',
  },
  avatar: {
    display: 'none',
  },
  profileName: {
    fontSize: '26px',
    fontWeight: 700,
    margin: 0,
    color: '#fff',
    letterSpacing: '0.5px',
    lineHeight: '1.2',
    textShadow: '0 0 20px rgba(20, 157, 221, 0.15)',
  },
  profileRole: {
    fontSize: '14px',
    fontWeight: 500,
    color: 'rgb(20, 157, 221)',
    marginTop: '8px',
    letterSpacing: '1px',
    textTransform: 'uppercase',
  },
  socialLinks: {
    display: 'flex',
    justifyContent: 'center',
    gap: '12px',
    marginBottom: '32px',
  },
  achortag: {
    textDecoration: 'none',
    color: 'white',
    display: 'flex',

    flexDirection: 'row',
    /* justify-content: center; */
    alignItems: 'center',
  },
  socialIcon: {
    width: '38px',
    height: '38px',
    background: 'linear-gradient(135deg, rgba(20, 157, 221, 0.12) 0%, rgba(20, 157, 221, 0.05) 100%)',
    border: '1px solid rgba(20, 157, 221, 0.2)',
    borderRadius: '10px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#149ddd',
    textDecoration: 'none',
    fontSize: '16px',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)',
  },
  navMenu: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
    flex: 1,
  },
  navButton: {
    background: 'transparent',
    border: 'none',
    color: '#a8a9b4',
    padding: '14px 18px',
    textAlign: 'left',
    fontSize: '15px',
    fontWeight: 500,
    cursor: 'pointer',
    borderRadius: '10px',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  navButtonHover: {
    background: 'rgba(20, 157, 221, 0.08)',
    color: '#fff',
    transform: 'translateX(4px)',
  },
  navButtonActive: {
    background: 'linear-gradient(135deg, rgba(20, 157, 221, 0.18) 0%, rgba(20, 157, 221, 0.08) 100%)',
    border: 'none',
    color: '#149ddd',
    padding: '14px 18px',
    textAlign: 'left',
    fontSize: '15px',
    fontWeight: 500,
    cursor: 'pointer',
    borderRadius: '10px',
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    position: 'relative',
    overflow: 'hidden',
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    boxShadow: '0 0 20px rgba(20, 157, 221, 0.15)',
  },
  navActiveBorder: {
    position: 'absolute',
    left: 0,
    top: '50%',
    transform: 'translateY(-50%)',
    width: '3px',
    height: '60%',
    background: 'linear-gradient(180deg, #149ddd 0%, #0c7ab5 100%)',
    borderRadius: '0 4px 4px 0',
  },
  navIcon: {
    fontSize: '18px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
  },
  mobileMenuBtn: {
    display: 'block',
    position: 'fixed',
    top: '20px',
    left: '20px',
    zIndex: 1100,
    background: '#149ddd',
    border: 'none',
    color: '#fff',
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    fontSize: '20px',
    cursor: 'pointer',
  },
  mainContent: {
    marginLeft: '21%',
    width: '79%',
    minHeight: '100vh',
    position: 'relative',
    boxSizing: 'border-box',
  },
  heroSection: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background:
      "url('/assets/img/Gemini_background.png') center center / cover no-repeat",
    textAlign: 'left',
    padding: '0 60px',
    position: 'relative',
  },
  heroBgOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    zIndex: 1,
  },
  heroContent: {
    position: 'relative',
    zIndex: 2,
    flex: '1',
    maxWidth: '600px',
  },
  heroImageContainer: {
    position: 'relative',
    zIndex: 2,
    flex: '0 0 auto',
    marginLeft: '40px',
  },
  heroImage: {
    width: '350px',
    height: '350px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '4px solid rgb(20, 157, 221)',
    boxShadow: '0 0 20px rgb(20, 157, 221), 0 0 40px rgba(20, 157, 221, 0.5)',
  },
  heroTitle: {
    fontSize: '47px',
    fontWeight: 700,
    marginBottom: '20px',
    color: '#fff',
  },
  heroSubtitle: {
    fontSize: '23px',
    color: 'rgb(20, 157, 221)',
  },
  highlight: {
    color: '#149ddd',
    borderBottom: '3px solid #149ddd',
  },
  section: {
    padding: '50px 20px',
    // background: "rgb(13 21 37)",
  },
  lightBg: {
    background: '#0d1117',
  },
  container: {
    maxWidth: '1140px',
    margin: '0 auto',
  },
  sectionTitle: {
    fontSize: '32px',
    fontWeight: 700,
    marginBottom: '30px',
    paddingBottom: '15px',
    borderBottom: '2px solid #2a2a3e',
  },
  aboutGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 2fr',
    gap: '40px',
    alignItems: 'start',
  },
  aboutImage: {
    aspectRatio: '1',
    background: 'linear-gradient(135deg, #149ddd 0%, #0c7ab5 100%)',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
    border: '2px solid rgba(20, 157, 221, 0.3)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
  },
  aboutProfileImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.3s ease',
  },
  aboutContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '30px',
  },
  aboutSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  aboutHeading: {
    fontSize: '28px',
    fontWeight: 700,
    color: '#fff',
    margin: 0,
    lineHeight: '1.3',
    marginBottom: '8px',
  },
  aboutSectionTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: 'rgb(20, 157, 221)',
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  aboutDescription: {
    color: '#a8a9b4',
    fontSize: '16px',
    lineHeight: '1.7',
    margin: 0,
    marginTop: '5px',
  },
  highlightsGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
  },
  highlightBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'rgba(20, 157, 221, 0.15)',
    border: '1px solid rgb(20, 157, 221)',
    padding: '10px 16px',
    borderRadius: '25px',
    transition: 'all 0.3s ease',
  },
  highlightIcon: {
    fontSize: '16px',
  },
  highlightText: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#fff',
  },
  contactGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '15px',
  },
  contactItem: {
    margin: 0,
    marginBottom: '8px',
  },
  contactLabel: {
    color: 'rgb(20, 157, 221)',
    fontSize: '14px',
    fontWeight: 600,
  },
  contactValue: {
    color: '#fff',
    fontSize: '14px',
  },
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '20px',
    marginTop: '30px',
  },
  infoText: {
    color: '#a8a9b4',
    marginBottom: '10px',
    fontSize: '14px',
    lineHeight: '1.6',
  },
  statsSection: {
    padding: '30px 20px',
    background: '#0d1117',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '18px',
  },
  statCard: {
    background:
      'linear-gradient(135deg, rgba(8,20,30,0.9) 0%, rgba(10,18,28,0.6) 100%)',
    border: '1px solid rgba(255,255,255,0.03)',
    padding: '18px',
    borderRadius: '14px',
    textAlign: 'center',
    boxShadow: '0 10px 30px rgba(2,6,23,0.6)',
    transition: 'transform 0.2s cubic-bezier(.2,.9,.2,1), box-shadow 0.2s ease',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    minHeight: '120px',
    willChange: 'transform, box-shadow',
    animation: 'fadeInUp 520ms ease both, float 6s ease-in-out infinite',
  },
  statIcon: {
    fontSize: '20px',
    marginBottom: '4px',
  },
  statValue: {
    fontSize: '34px',
    fontWeight: 800,
    color: '#12b0ff',
    marginBottom: '2px',
  },
  statLabel: {
    color: '#9aa3ad',
    fontSize: '13px',
    textAlign: 'center',
  },
  statIconCircle: {
    width: '56px',
    height: '56px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg,#0d2740 0%, #072033 100%)',
    border: '1px solid rgba(20,157,221,0.08)',
    boxShadow: 'inset 0 -6px 16px rgba(0,0,0,0.6)',
    color: '#12b0ff',
    fontSize: '20px',
  },
  skillsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '30px',
  },
  skillItem: {
    marginBottom: '20px',
  },
  skillHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  progressBar: {
    height: '10px',
    background: '#2a2a3e',
    borderRadius: '5px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #149ddd 0%, #0c7ab5 100%)',
    transition: 'width 0.3s ease',
  },
  resumeGrid: {
    display: 'grid',
    // gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gridTemplateRows: 'repeat(auto-fit, minmax(400px, 1fr))',
    gap: '40px',
  },
  resumeSubtitle: {
    fontSize: '26px',
    marginBottom: '20px',
  },
  // start change
  summaryContainer: {
    // background: "rgb(26, 31, 46)",
    // padding: "25px",
    borderRadius: '10px',
    marginBottom: '40px',
    // borderLeft: "3px solid rgb(20, 157, 221)",
  },
  heading: {
    fontSize: '26px',
    marginBottom: '15px',
    color: '#fff',
  },
  paragraph: {
    color: 'rgb(168, 169, 180)',
    lineHeight: '1.6',
  },
  // end
  resumeItem: {
    background: '#1a1f2e',
    padding: '25px',
    borderRadius: '10px',
    marginBottom: '20px',
    borderLeft: '3px solid #149ddd',
  },
  badge: {
    display: 'inline-block',
    background: '#149ddd',
    color: '#fff',
    padding: '5px 15px',
    borderRadius: '20px',
    fontSize: '13px',
    marginBottom: '10px',
    marginTop: '5px',
  },
  descText: {
    color: '#a8a9b4',
  },
  list: {
    marginTop: '15px',
    paddingLeft: '20px',
    color: '#a8a9b4',
  },
  portfolioFilters: {
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
    marginBottom: '40px',
    flexWrap: 'wrap',
  },
  filterBtn: {
    padding: '10px 26px',
    background: 'transparent',
    border: '2px solid rgba(20, 157, 221, 0.5)',
    color: '#149ddd',
    borderRadius: '24px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    outline: 'none',
    textTransform: 'capitalize',
  },
  filterBtnActive: {
    padding: '10px 26px',
    background:
      'linear-gradient(135deg, rgba(20, 157, 221, 0.9) 0%, rgba(12, 122, 181, 0.9) 100%)',
    border: '2px solid rgba(125, 211, 255, 0.8)',
    color: '#fff',
    borderRadius: '24px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    outline: 'none',
    textTransform: 'capitalize',
    boxShadow: '0 8px 24px rgba(20, 157, 221, 0.3)',
  },
  portfolioGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '24px',
  },
  portfolioCard: {
    background:
      'linear-gradient(135deg, rgba(20, 157, 221, 0.08) 0%, rgba(22, 29, 41, 0.9) 100%)',
    border: '1px solid rgba(20, 157, 221, 0.15)',
    borderRadius: '14px',
    overflow: 'hidden',
    transition: 'all 0.3s ease',
  },
  portfolioImg: {
    aspectRatio: '16/9',
    background: 'linear-gradient(135deg, #149ddd 0%, #0c7ab5 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
  },
  portfolioInfo: {
    padding: '20px',
  },
  portfolioDesc: {
    color: '#a8a9b4',
    fontSize: '13px',
    lineHeight: '1.6',
    marginBottom: '12px',
  },
  projectTechStack: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginBottom: '12px',
  },
  techBadge: {
    background: 'rgba(20, 157, 221, 0.15)',
    color: '#149ddd',
    padding: '4px 10px',
    borderRadius: '12px',
    fontSize: '11px',
    fontWeight: 500,
  },
  projectHighlights: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginBottom: '16px',
  },
  highlightPill: {
    background: 'rgba(168, 169, 180, 0.1)',
    color: '#a8a9b4',
    padding: '4px 10px',
    borderRadius: '12px',
    fontSize: '11px',
  },
  servicesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '25px',
  },
  serviceCard: {
    background: '#1a1f2e',
    padding: '30px',
    borderRadius: '10px',
  },
  serviceIcon: {
    fontSize: '48px',
    marginBottom: '20px',
  },
  serviceTitle: {
    marginBottom: '15px',
  },
  serviceDesc: {
    color: '#a8a9b4',
    fontSize: '14px',
    lineHeight: 1.6,
  },
  contactGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '40px',
  },
  groupSection: {
    padding: '40px 20px',
    background: 'transparent',
  },
  groupHeading: {
    fontSize: '30px',
    fontWeight: 700,
    marginBottom: '22px',
    color: '#fff',
    borderBottom: '2px solid rgba(42,42,62,0.8)',
    paddingBottom: '12px',
  },
  infoCard: {
    background:
      'linear-gradient(135deg, rgba(20, 157, 221, 0.1) 0%, rgba(22, 29, 41, 0.8) 100%)',
    border: '1px solid rgba(20, 157, 221, 0.2)',
    padding: '25px',
    borderRadius: '14px',
    boxShadow:
      '0 4px 20px rgba(0, 0, 0, 0.3), 0 0 30px rgba(0, 210, 255, 0.06)',
    marginBottom: '12px',
  },
  contactForm: {
    background: '#1a1f2e',
    padding: '30px',
    borderRadius: '10px',
  },
  input: {
    width: '100%',
    padding: '12px',
    marginBottom: '15px',
    background: '#0d1525',
    border: '1px solid #2a2a3e',
    borderRadius: '5px',
    color: '#fff',
    fontSize: '14px',
    boxSizing: 'border-box',
  },
  textarea: {
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  submitBtn: {
    width: '100%',
    padding: '15px',
    background: '#149ddd',
    border: 'none',
    borderRadius: '25px',
    color: '#fff',
    fontSize: '16px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  footer: {
    background: '#0d1525',
    padding: '30px 20px',
    textAlign: 'center',
    borderTop: '1px solid #2a2a3e',
  },
  credits: {
    fontSize: '13px',
    color: '#a8a9b4',
    marginTop: '5px',
  },
  scrollTop: {
    position: 'fixed',
    bottom: '30px',
    right: '30px',
    width: '44px',
    height: '44px',
    background: '#149ddd',
    border: 'none',
    borderRadius: '50%',
    color: '#fff',
    fontSize: '24px',
    cursor: 'pointer',
    zIndex: 999,
  },
  //dialog css
  paper: {
    borderRadius: '12px',
    padding: '20px',
    backgroundColor: '#1e1e2f',
    color: '#fff',
  },
  title: {
    fontSize: '1.8rem',
    fontWeight: 600,
    marginBottom: '1rem',
  },
  video: {
    width: '100%',
    borderRadius: '8px',
    marginBottom: '1rem',
  },
  text: {
    marginBottom: '0.75rem',
    lineHeight: 1.5,
  },
  link: {
    color: '#4fc3f7',
    textDecoration: 'underline',
  },
  closeButton: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    color: '#fff',
    background: 'rgba(0,0,0,0.3)',
  },

  // ── Resume / Professional Experience ───────────────────────

  resumeTopGrid: {
    display: 'grid',
    gridTemplateColumns: '3fr 2fr',
    gap: '24px',
    marginBottom: '52px',
    alignItems: 'stretch',
  },

  // Summary card
  resumeSummaryCard: {
    // background: 'linear-gradient(135deg, rgba(20,157,221,0.04) 0%, rgba(18,24,38,0.85) 100%)',
    border: '1px solid rgba(20,157,221,0.15)',
    borderRadius: '16px',
    padding: '28px',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
    transition: 'border-color 0.3s ease, box-shadow 0.3s ease, transform 0.3s ease',
  },
  summaryAccentBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: '4px',
    height: '100%',
    background: 'linear-gradient(180deg, #149ddd 0%, #0c7ab5 100%)',
    borderRadius: '16px 0 0 16px',
  },
  summaryTitle: {
    fontSize: '28px',
    fontWeight: 700,
    color: '#fff',
    margin: '0 0 12px',
    lineHeight: '1.3',
  },
  summaryBody: {
    color: '#a8a9b4',
    fontSize: '16px',
    lineHeight: '1.7',
    margin: '0 0 20px',
  },
  summaryPillRow: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  summaryPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    fontWeight: 500,
    color: '#fff',
    background: 'rgba(20, 157, 221, 0.15)',
    border: '1px solid rgb(20, 157, 221)',
    padding: '10px 16px',
    borderRadius: '25px',
    transition: 'all 0.3s ease',
  },
  summaryPillGreen: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    fontWeight: 500,
    color: '#fff',
    background: 'rgba(74,222,128,0.15)',
    border: '1px solid rgba(74,222,128,0.5)',
    padding: '10px 16px',
    borderRadius: '25px',
    transition: 'all 0.3s ease',
  },

  // Stats quad
  statsQuad: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '14px',
  },
  statCardNew: {
    background: 'linear-gradient(135deg, rgba(8,20,30,0.92) 0%, rgba(12,20,30,0.75) 100%)',
    border: '1px solid rgba(20,157,221,0.1)',
    borderRadius: '12px',
    padding: '18px 14px',
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    cursor: 'default',
    transition: 'transform 0.25s ease, border-color 0.25s ease, box-shadow 0.25s ease',
  },
  statIconBox: {
    width: '42px',
    height: '42px',
    borderRadius: '10px',
    background: 'linear-gradient(135deg, rgba(20,157,221,0.15) 0%, rgba(12,122,181,0.08) 100%)',
    border: '1px solid rgba(20,157,221,0.2)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#149ddd',
    marginBottom: '6px',
  },
  statNumVal: {
    fontSize: '28px',
    fontWeight: 800,
    color: '#12b0ff',
    lineHeight: 1,
  },
  statNumLabel: {
    fontSize: '12px',
    fontWeight: 600,
    color: '#e2e4ea',
  },
  statNumSub: {
    fontSize: '10px',
    color: '#556070',
    lineHeight: '1.4',
  },

  // Work-history divider
  expDividerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    margin: '0 0 40px',
  },
  dividerLine: {
    flex: 1,
    height: '1px',
    background: 'linear-gradient(90deg, transparent, rgba(20,157,221,0.3), transparent)',
  },
  dividerCaption: {
    fontSize: '10px',
    fontWeight: 700,
    letterSpacing: '3px',
    textTransform: 'uppercase',
    color: '#149ddd',
    whiteSpace: 'nowrap',
    opacity: 0.9,
  },

  // Timeline
  timelineWrapper: {
    position: 'relative',
    paddingLeft: '36px',
  },
  timelineRailLine: {
    position: 'absolute',
    left: '7px',
    top: '14px',
    bottom: '14px',
    width: '2px',
    background: 'linear-gradient(180deg, #149ddd 0%, rgba(20,157,221,0.2) 65%, transparent 100%)',
    borderRadius: '2px',
  },
  timelineJobItem: {
    position: 'relative',
    marginBottom: '22px',
    transition: 'opacity 0.5s ease, transform 0.5s ease',
  },
  timelineDotDefault: {
    position: 'absolute',
    left: '-36px',
    top: '20px',
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    background: '#040b14',
    border: '2px solid rgba(20,157,221,0.35)',
    zIndex: 2,
    transition: 'border-color 0.3s ease',
  },
  timelineDotActive: {
    position: 'absolute',
    left: '-36px',
    top: '20px',
    width: '16px',
    height: '16px',
    borderRadius: '50%',
    background: 'rgba(20,157,221,0.2)',
    border: '2px solid #149ddd',
    boxShadow: '0 0 8px rgba(20,157,221,0.4)',
    zIndex: 2,
  },

  // Experience card
  expCard: {
    background: 'linear-gradient(135deg, rgba(20,157,221,0.04) 0%, rgba(18,24,38,0.85) 100%)',
    border: '1px solid rgba(20,157,221,0.15)',
    borderRadius: '16px',
    padding: '24px 26px',
    transition: 'border-color 0.3s ease, box-shadow 0.3s ease, transform 0.3s ease',
  },
  expCardHovered: {
    borderColor: 'rgba(20,157,221,0.38)',
    boxShadow: '0 8px 40px rgba(20,157,221,0.09)',
    transform: 'translateY(-2px)',
  },
  expCardTopRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '14px',
    marginBottom: '14px',
    flexWrap: 'wrap',
  },
  expCompanyName: {
    fontSize: '18px',
    fontWeight: 700,
    color: '#149ddd',
    margin: '0 0 6px',
  },
  expRoleTitle: {
    fontSize: '15px',
    fontWeight: 500,
    color: '#fff',
    margin: 0,
    lineHeight: '1.5',
  },
  expBadgeGroup: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '5px',
    flexShrink: 0,
  },
  expPeriodPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 600,
    background: 'rgba(20,157,221,0.1)',
    color: '#149ddd',
    border: '1px solid rgba(20,157,221,0.25)',
    padding: '6px 12px',
    borderRadius: '20px',
  },
  expPeriodPillActive: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    fontWeight: 600,
    background: 'rgba(20,157,221,0.18)',
    color: '#12b0ff',
    border: '1px solid rgba(20,157,221,0.45)',
    padding: '6px 12px',
    borderRadius: '20px',
  },
  expLocationPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '12px',
    color: '#a8a9b4',
  },

  // Bullet list
  expBulletList: {
    listStyle: 'none',
    padding: 0,
    margin: '0 0 14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  expBulletItem: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '10px',
    fontSize: '15px',
    color: '#a8a9b4',
    lineHeight: '1.7',
  },
  bulletDot: {
    display: 'inline-block',
    minWidth: '6px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: 'rgba(20,157,221,0.65)',
    marginTop: '8px',
    flexShrink: 0,
  },

  // Tech chip tags
  techTagsRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    paddingTop: '12px',
    borderTop: '1px solid rgba(255,255,255,0.05)',
  },
  techChip: {
    display: 'inline-flex',
    alignItems: 'center',
    fontSize: '14px',
    fontWeight: 500,
    color: '#fff',
    background: 'rgba(20, 157, 221, 0.15)',
    border: '1px solid rgb(20, 157, 221)',
    padding: '10px 16px',
    borderRadius: '25px',
    cursor: 'default',
    transition: 'all 0.3s ease',
  },
};
