import { manageImages } from './manageImages';

const { src: heroImg } = manageImages.heroImage;
// const images = require("../public/assets/img/hero-img-1.jpg");
// public\assets\img\hero-img-1.jpg

export const styles = {
  app: {
    fontFamily:
      '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    color: '#fff',
    background: '#040b14',
    minHeight: '100vh',
  },
  sidebar: {
    position: 'fixed', // make it always stay visible
    left: 0,
    top: 0,
    bottom: 0,
    width: '21%',
    display: 'flex',
    flexDirection: 'column',
    background: 'rgb(30, 30, 46)',
    borderRight: '1px solid rgb(42, 42, 62)',
    overflowY: 'auto',
    zIndex: 1000,
  },
  sidebarOpen: {
    transform: 'translateX(0)',
  },
  sidebarContent: {
    padding: '30px',
  },
  profileSection: {
    textAlign: 'center',
    marginBottom: '30px',
  },
  avatar: {
    width: '120px',
    height: '120px',
    margin: '0 auto 20px',
    background: 'linear-gradient(135deg, #149ddd 0%, #0c7ab5 100%)',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '48px',
    fontWeight: 'bold',
  },
  profileName: {
    fontSize: '24px',
    fontWeight: 600,
    margin: 0,
  },
  socialLinks: {
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
    marginBottom: '30px',
  },
  achortag: {
    textDecoration: 'none',
    color: 'white',
    display: 'flex',

    flexDirection: 'row',
    /* justify-content: center; */
    alignItems: 'center',
  },
  socialIcon: {
    width: '31px',
    height: '31px',
    background: '#2a2a3e',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#149ddd',
    textDecoration: 'none',
    fontSize: '12px',
    transition: 'all 0.3s ease',
  },
  navMenu: {
    display: 'flex',
    flexDirection: 'column',
    gap: '5px',
  },
  navButton: {
    background: 'transparent',
    border: 'none',
    color: '#a8a9b4',
    padding: '12px 15px',
    textAlign: 'left',
    fontSize: '15px',
    cursor: 'pointer',
    borderRadius: '5px',
    transition: 'all 0.3s ease',
  },
  navButtonActive: {
    background: 'rgba(20, 157, 221, 0.15)',
    border: 'none',
    color: 'rgb(20, 157, 221)',
    padding: '12px 15px',
    textAlign: 'left',
    fontSize: '15px',
    cursor: 'pointer',
    borderRadius: '5px',
    transition: 'all 0.3s ease',
  },
  mobileMenuBtn: {
    display: 'block',
    position: 'fixed',
    top: '20px',
    left: '20px',
    zIndex: 1100,
    background: '#149ddd',
    border: 'none',
    color: '#fff',
    width: '44px',
    height: '44px',
    borderRadius: '50%',
    fontSize: '20px',
    cursor: 'pointer',
  },
  mainContent: {
    marginLeft: '21%',
    width: '79%',
    minHeight: '100vh',
    position: 'relative',
    boxSizing: 'border-box',
  },
  heroSection: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background:
      "url('/assets/img/Gemini_background.png') center center / cover no-repeat",
    textAlign: 'left',
    padding: '0 60px',
    position: 'relative',
  },
  heroBgOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    zIndex: 1,
  },
  heroContent: {
    position: 'relative',
    zIndex: 2,
    flex: '1',
    maxWidth: '600px',
  },
  heroImageContainer: {
    position: 'relative',
    zIndex: 2,
    flex: '0 0 auto',
    marginLeft: '40px',
  },
  heroImage: {
    width: '350px',
    height: '350px',
    borderRadius: '50%',
    objectFit: 'cover',
    border: '4px solid rgb(20, 157, 221)',
    boxShadow: '0 0 20px rgb(20, 157, 221), 0 0 40px rgba(20, 157, 221, 0.5)',
  },
  heroTitle: {
    fontSize: '47px',
    fontWeight: 700,
    marginBottom: '20px',
    color: '#fff',
  },
  heroSubtitle: {
    fontSize: '23px',
    color: 'rgb(20, 157, 221)',
  },
  highlight: {
    color: '#149ddd',
    borderBottom: '3px solid #149ddd',
  },
  section: {
    padding: '50px 20px',
    // background: "rgb(13 21 37)",
  },
  lightBg: {
    background: '#0d1117',
  },
  container: {
    maxWidth: '1140px',
    margin: '0 auto',
  },
  sectionTitle: {
    fontSize: '32px',
    fontWeight: 700,
    marginBottom: '30px',
    paddingBottom: '15px',
    borderBottom: '2px solid #2a2a3e',
  },
  aboutGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 2fr',
    gap: '40px',
    alignItems: 'start',
  },
  aboutImage: {
    aspectRatio: '1',
    background: 'linear-gradient(135deg, #149ddd 0%, #0c7ab5 100%)',
    borderRadius: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.3)',
    border: '2px solid rgba(20, 157, 221, 0.3)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease',
  },
  aboutProfileImg: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    transition: 'transform 0.3s ease',
  },
  aboutContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: '30px',
  },
  aboutSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  aboutHeading: {
    fontSize: '28px',
    fontWeight: 700,
    color: '#fff',
    margin: 0,
    lineHeight: '1.3',
    marginBottom: '8px',
  },
  aboutSectionTitle: {
    fontSize: '16px',
    fontWeight: 600,
    color: 'rgb(20, 157, 221)',
    marginBottom: '8px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
  },
  aboutDescription: {
    color: '#a8a9b4',
    fontSize: '16px',
    lineHeight: '1.7',
    margin: 0,
    marginTop: '5px',
  },
  highlightsGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
  },
  highlightBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'rgba(20, 157, 221, 0.15)',
    border: '1px solid rgb(20, 157, 221)',
    padding: '10px 16px',
    borderRadius: '25px',
    transition: 'all 0.3s ease',
  },
  highlightIcon: {
    fontSize: '16px',
  },
  highlightText: {
    fontSize: '14px',
    fontWeight: 500,
    color: '#fff',
  },
  contactGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '15px',
  },
  contactItem: {
    margin: 0,
    marginBottom: '8px',
  },
  contactLabel: {
    color: 'rgb(20, 157, 221)',
    fontSize: '14px',
    fontWeight: 600,
  },
  contactValue: {
    color: '#fff',
    fontSize: '14px',
  },
  infoGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '20px',
    marginTop: '30px',
  },
  infoText: {
    color: '#a8a9b4',
    marginBottom: '10px',
    fontSize: '14px',
    lineHeight: '1.6',
  },
  statsSection: {
    padding: '30px 20px',
    background: '#0d1117',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))',
    gap: '18px',
  },
  statCard: {
    background:
      'linear-gradient(135deg, rgba(8,20,30,0.9) 0%, rgba(10,18,28,0.6) 100%)',
    border: '1px solid rgba(255,255,255,0.03)',
    padding: '18px',
    borderRadius: '14px',
    textAlign: 'center',
    boxShadow: '0 10px 30px rgba(2,6,23,0.6)',
    transition: 'transform 0.2s cubic-bezier(.2,.9,.2,1), box-shadow 0.2s ease',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    minHeight: '120px',
    willChange: 'transform, box-shadow',
    animation: 'fadeInUp 520ms ease both, float 6s ease-in-out infinite',
  },
  statIcon: {
    fontSize: '20px',
    marginBottom: '4px',
  },
  statValue: {
    fontSize: '34px',
    fontWeight: 800,
    color: '#12b0ff',
    marginBottom: '2px',
  },
  statLabel: {
    color: '#9aa3ad',
    fontSize: '13px',
    textAlign: 'center',
  },
  statIconCircle: {
    width: '56px',
    height: '56px',
    borderRadius: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'linear-gradient(135deg,#0d2740 0%, #072033 100%)',
    border: '1px solid rgba(20,157,221,0.08)',
    boxShadow: 'inset 0 -6px 16px rgba(0,0,0,0.6)',
    color: '#12b0ff',
    fontSize: '20px',
  },
  skillsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '30px',
  },
  skillItem: {
    marginBottom: '20px',
  },
  skillHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  progressBar: {
    height: '10px',
    background: '#2a2a3e',
    borderRadius: '5px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: 'linear-gradient(90deg, #149ddd 0%, #0c7ab5 100%)',
    transition: 'width 0.3s ease',
  },
  resumeGrid: {
    display: 'grid',
    // gridTemplateColumns: "repeat(auto-fit, minmax(400px, 1fr))",
    gridTemplateRows: 'repeat(auto-fit, minmax(400px, 1fr))',
    gap: '40px',
  },
  resumeSubtitle: {
    fontSize: '26px',
    marginBottom: '20px',
  },
  // start change
  summaryContainer: {
    // background: "rgb(26, 31, 46)",
    // padding: "25px",
    borderRadius: '10px',
    marginBottom: '40px',
    // borderLeft: "3px solid rgb(20, 157, 221)",
  },
  heading: {
    fontSize: '26px',
    marginBottom: '15px',
    color: '#fff',
  },
  paragraph: {
    color: 'rgb(168, 169, 180)',
    lineHeight: '1.6',
  },
  // end
  resumeItem: {
    background: '#1a1f2e',
    padding: '25px',
    borderRadius: '10px',
    marginBottom: '20px',
    borderLeft: '3px solid #149ddd',
  },
  badge: {
    display: 'inline-block',
    background: '#149ddd',
    color: '#fff',
    padding: '5px 15px',
    borderRadius: '20px',
    fontSize: '13px',
    marginBottom: '10px',
    marginTop: '5px',
  },
  descText: {
    color: '#a8a9b4',
  },
  list: {
    marginTop: '15px',
    paddingLeft: '20px',
    color: '#a8a9b4',
  },
  portfolioFilters: {
    display: 'flex',
    justifyContent: 'center',
    gap: '10px',
    marginBottom: '40px',
    flexWrap: 'wrap',
  },
  filterBtn: {
    padding: '10px 26px',
    background: 'transparent',
    border: '2px solid rgba(20, 157, 221, 0.5)',
    color: '#149ddd',
    borderRadius: '24px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    outline: 'none',
    textTransform: 'capitalize',
  },
  filterBtnActive: {
    padding: '10px 26px',
    background:
      'linear-gradient(135deg, rgba(20, 157, 221, 0.9) 0%, rgba(12, 122, 181, 0.9) 100%)',
    border: '2px solid rgba(125, 211, 255, 0.8)',
    color: '#fff',
    borderRadius: '24px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 600,
    transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
    outline: 'none',
    textTransform: 'capitalize',
    boxShadow: '0 8px 24px rgba(20, 157, 221, 0.3)',
  },
  portfolioGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '24px',
  },
  portfolioCard: {
    background:
      'linear-gradient(135deg, rgba(20, 157, 221, 0.08) 0%, rgba(22, 29, 41, 0.9) 100%)',
    border: '1px solid rgba(20, 157, 221, 0.15)',
    borderRadius: '14px',
    overflow: 'hidden',
    transition: 'all 0.3s ease',
  },
  portfolioImg: {
    aspectRatio: '16/9',
    background: 'linear-gradient(135deg, #149ddd 0%, #0c7ab5 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 600,
  },
  portfolioInfo: {
    padding: '20px',
  },
  portfolioDesc: {
    color: '#a8a9b4',
    fontSize: '13px',
    lineHeight: '1.6',
    marginBottom: '12px',
  },
  projectTechStack: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginBottom: '12px',
  },
  techBadge: {
    background: 'rgba(20, 157, 221, 0.15)',
    color: '#149ddd',
    padding: '4px 10px',
    borderRadius: '12px',
    fontSize: '11px',
    fontWeight: 500,
  },
  projectHighlights: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginBottom: '16px',
  },
  highlightPill: {
    background: 'rgba(168, 169, 180, 0.1)',
    color: '#a8a9b4',
    padding: '4px 10px',
    borderRadius: '12px',
    fontSize: '11px',
  },
  servicesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: '25px',
  },
  serviceCard: {
    background: '#1a1f2e',
    padding: '30px',
    borderRadius: '10px',
  },
  serviceIcon: {
    fontSize: '48px',
    marginBottom: '20px',
  },
  serviceTitle: {
    marginBottom: '15px',
  },
  serviceDesc: {
    color: '#a8a9b4',
    fontSize: '14px',
    lineHeight: 1.6,
  },
  contactGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
    gap: '40px',
  },
  groupSection: {
    padding: '40px 20px',
    background: 'transparent',
  },
  groupHeading: {
    fontSize: '30px',
    fontWeight: 700,
    marginBottom: '22px',
    color: '#fff',
    borderBottom: '2px solid rgba(42,42,62,0.8)',
    paddingBottom: '12px',
  },
  infoCard: {
    background:
      'linear-gradient(135deg, rgba(20, 157, 221, 0.1) 0%, rgba(22, 29, 41, 0.8) 100%)',
    border: '1px solid rgba(20, 157, 221, 0.2)',
    padding: '25px',
    borderRadius: '14px',
    boxShadow:
      '0 4px 20px rgba(0, 0, 0, 0.3), 0 0 30px rgba(0, 210, 255, 0.06)',
    marginBottom: '12px',
  },
  contactForm: {
    background: '#1a1f2e',
    padding: '30px',
    borderRadius: '10px',
  },
  input: {
    width: '100%',
    padding: '12px',
    marginBottom: '15px',
    background: '#0d1525',
    border: '1px solid #2a2a3e',
    borderRadius: '5px',
    color: '#fff',
    fontSize: '14px',
    boxSizing: 'border-box',
  },
  textarea: {
    resize: 'vertical',
    fontFamily: 'inherit',
  },
  submitBtn: {
    width: '100%',
    padding: '15px',
    background: '#149ddd',
    border: 'none',
    borderRadius: '25px',
    color: '#fff',
    fontSize: '16px',
    fontWeight: 600,
    cursor: 'pointer',
  },
  footer: {
    background: '#0d1525',
    padding: '30px 20px',
    textAlign: 'center',
    borderTop: '1px solid #2a2a3e',
  },
  credits: {
    fontSize: '13px',
    color: '#a8a9b4',
    marginTop: '5px',
  },
  scrollTop: {
    position: 'fixed',
    bottom: '30px',
    right: '30px',
    width: '44px',
    height: '44px',
    background: '#149ddd',
    border: 'none',
    borderRadius: '50%',
    color: '#fff',
    fontSize: '24px',
    cursor: 'pointer',
    zIndex: 999,
  },
  //dialog css
  paper: {
    borderRadius: '12px',
    padding: '20px',
    backgroundColor: '#1e1e2f',
    color: '#fff',
  },
  title: {
    fontSize: '1.8rem',
    fontWeight: 600,
    marginBottom: '1rem',
  },
  video: {
    width: '100%',
    borderRadius: '8px',
    marginBottom: '1rem',
  },
  text: {
    marginBottom: '0.75rem',
    lineHeight: 1.5,
  },
  link: {
    color: '#4fc3f7',
    textDecoration: 'underline',
  },
  closeButton: {
    position: 'absolute',
    top: '8px',
    right: '8px',
    color: '#fff',
    background: 'rgba(0,0,0,0.3)',
  },
};
